Remove list action.
After ensuring that any valid paths could be handled, listing the
snapshots became too problematic. There's no good way to list files that
could potentially have newlines (even if it's a remote possibility).
Since the list action is not crucial to the way the application
function, I decided to remove it.

diff --git a/bin/btrfs-snapshots b/bin/btrfs-snapshots
--- a/bin/btrfs-snapshots
+++ b/bin/btrfs-snapshots
@@ -67,10 +67,15 @@ while [[ -v 1 ]]; do
     shift
 done
 
-action=${1:-list}
+if [[ ! -v 1 ]]; then
+    printf "$TEXT_ACTION_MISSING\n" >&2
+    exit 1
+fi
+
+action=$1
 
 case $action in
-create | prune | list) ;;
+create | prune) ;;
 *)
     printf "$TEXT_ACTION_INVALID\n" "$action" >&2
     exit 1
