test: migrate test suites to bats
I'm tired of maintaining my own test assertion library.

In the process of migrating the test code to bats, some test assumptions
got refined and ended up changing the tests a bit.

The most impacting change, in my opinion, is a conversion to generating
fake commands at the exact spot where they're needed to be more precise
about what's being tested. This ended up obviating the need for a static
directory of fake commands.

This new way of creating fakes inspired me to refine the tests for the
main btrfs-snapshots command which allowed me to fake the core library
for it and only test the specific things that the command does and not
duplicating the tests that already covered the core functionality. This
made the tests for the main command much simpler.

The discovery was made that I did not need to have a full set of
timestamp ordering functions, and was only using one (timestamp_gt).
While digging around in the pruning algorithm, I discovered that, given
that the snapshots were being iterated in order, the single function was
not needed at all, and the entire set and the corresponding tests were
deleted. The resulting pruning algorithm is a bit tidier and easier to
read and reason about.

While messing with the pruning algorithm, I realized that the test
coverage for it was not as thorough as it could be, and added some
additional testing. I'm still not sure if it's adequate enough coverage
to check my assumptions of the behavior, but it's an improvement.

diff --git a/bin/btrfs-snapshots b/bin/btrfs-snapshots
--- a/bin/btrfs-snapshots
+++ b/bin/btrfs-snapshots
@@ -53,7 +53,12 @@ while (($# > 0)); do
     fi
 done
 
-action_name=${1:?missing action}
+if [[ ! -v 1 ]]; then
+    printf "%s: missing action\n" "$SELF_NAME" >&2
+    exit 64
+fi
+
+action_name=$1
 shift
 
 if [[ ! $action_name =~ ^(list|create|prune)$ ]]; then
