Improve interface and remove unnecessary restriction

diff --git a/bin/btrfs-snapshots b/bin/btrfs-snapshots
--- a/bin/btrfs-snapshots
+++ b/bin/btrfs-snapshots
@@ -13,15 +13,17 @@ usage="Manage timestamped collections of btrfs snapshots.
 Usage:
     $self_name -h|--help
     $self_name -v|--version
-    $self_name ACTION [NAME...]
-
-Arguments:
-    ACTION    action to perform on selected profiles
-    NAME      profile name to perform action on (default: all)
+    $self_name profiles
+    $self_name list|create|prune [NAME...]
 
 Actions:
-    create    create a new snapshot in the configured location
-    prune     delete snapshots that fall outside of defined limits
+    profiles    print profile names to stdout
+    list        print snapshot paths to stdout
+    create      create a new snapshot in the configured location
+    prune       delete snapshots that fall outside of defined limits
+
+Arguments:
+    NAME        profile name to perform action on (default: all)
 
 Environment:
     ${self_name^^}_CONFIG_DIR[=${CONFIG_DIR@Q}]
@@ -31,7 +33,7 @@ See also:
     $self_name(8)
 "
 
-version="0.9.2"
+version="0.10.0"
 
 if (($# > 0)); then
     if [[ $1 == -h || $1 == --help ]]; then
@@ -48,7 +50,7 @@ fi
 action_name=${1:?missing action}
 shift
 
-if [[ ! $action_name =~ ^(create|prune)$ ]]; then
+if [[ ! $action_name =~ ^(profiles|list|create|prune)$ ]]; then
     printf "%s: invalid action: %s\n" "$0" "$action_name" >&2
     exit 1
 fi
@@ -56,52 +58,48 @@ fi
 export PROFILES_DIR=$CONFIG_DIR/profile.d
 export DEFAULTS_FILE=$CONFIG_DIR/defaults.conf
 
+if [[ $action_name == profiles ]]; then
+    do_profiles
+    exit
+fi
+
+profile_names=()
+declare -A profile_files=()
+
+for profile_file in "$PROFILES_DIR"/*.conf; do
+    profile_name=${profile_file##*/}
+    profile_name=${profile_name%.conf}
+    profile_names+=("$profile_name")
+    profile_files[$profile_name]=$profile_file
+done
+
 declare -A profiles_selected=()
 
 for profile_name in "$@"; do
-    profile_file=$PROFILES_DIR/$profile_name.conf
-
-    if [[ ! -f $profile_file ]]; then
-        printf "%s: profile does not exist: %q\n" "$0" "$profile_file" >&2
+    if [[ ! -v profile_files[$profile_name] ]]; then
+        printf "%s: profile does not exist: %q\n" "$0" "$profile_name" >&2
         exit 2
     fi
 
-    profiles_selected[$profile_file]=1
+    profiles_selected[$profile_name]=1
 done
 
-declare -A snapshots_seen=()
+if ((${#profiles_selected[@]} == 0)); then
+    for profile_name in "${profile_names[@]}"; do
+        profiles_selected[$profile_name]=1
+    done
+fi
 
-for profile_file in "$PROFILES_DIR"/*.conf; do
-    if ! load_profile "$profile_file"; then
-        printf "%s: unable to load profile: %q\n" "$0" "$profile_file" >&2
+for profile_name in "${profile_names[@]}"; do
+    [[ -v profiles_selected[$profile_name] ]] || continue
+
+    if ! load_profile "${profile_files[$profile_name]}"; then
+        printf "%s: unable to load profile: %q\n" "$0" "$profile_name" >&2
         exit 2
     fi
 
-    if [[ -v snapshots_seen[$SNAPSHOTS] ]]; then
-        printf "%s: the same value for SNAPSHOTS is used for multiple profiles: %q\n" "$0" "$SNAPSHOTS" >&2
-        exit 2
-    fi
-
-    snapshots_seen[$SNAPSHOTS]=1
-done
-
-declare -A profiles_seen=()
-
-for profile_file in "$PROFILES_DIR"/*.conf; do
-    if ((${#profiles_selected[@]} > 0)) && [[ ! -v profiles_selected[$profile_file] ]]; then
-        continue
-    fi
-
-    if [[ -v profiles_seen[$profile_file] ]]; then
-        continue
-    fi
-
-    profiles_seen[$profile_file]=1
-
-    load_profile "$profile_file"
-
-    if ! action_"$action_name"; then
-        printf "%s: unable to perform action '%s' for profile: %q\n" "$0" "$action_name" "$profile_file" >&2
+    if ! do_"$action_name"; then
+        printf "%s: unable to perform action '%s' for profile: %q\n" "$0" "$action_name" "$profile_name" >&2
         exit 1
     fi
 done
