Tinkering

diff --git a/bin/btrfs-snapshots b/bin/btrfs-snapshots
--- a/bin/btrfs-snapshots
+++ b/bin/btrfs-snapshots
@@ -5,8 +5,8 @@ shopt -s nullglob
 
 self_name=${0##*/}
 
-LIB_DIR=${BTRFS_SNAPSHOTS_LIB_DIR:-/usr/local/lib/$self_name}
-CONFIG_DIR=${BTRFS_SNAPSHOTS_CONFIG_DIR:-/usr/local/etc/$self_name}
+export LIB_DIR=${BTRFS_SNAPSHOTS_LIB_DIR:-/usr/local/lib/$self_name}
+export CONFIG_DIR=${BTRFS_SNAPSHOTS_CONFIG_DIR:-/usr/local/etc/$self_name}
 
 usage="Manage timestamped collections of btrfs snapshots.
 
@@ -14,16 +14,17 @@ Usage:
     $self_name [OPTIONS] ACTION
 
 Options:
-    -h              show this help text and exit
+    -h    show this help text and exit
+
     -p NAME         perform action on profile NAME
     -C DIRECTORY    use DIRECTORY for configuration
 
 Arguments:
-    ACTION          action to perform on selected profiles
+    ACTION    action to perform on selected profiles
 
 Actions:
-    create          create a new snapshot in the configured location
-    prune           delete snapshots that fall outside of defined limits
+    create    create a new snapshot in the configured location
+    prune     delete snapshots that fall outside of defined limits
 
 Environment:
     ${self_name^^}_CONFIG_DIR[=${CONFIG_DIR@Q}]
@@ -37,14 +38,13 @@ See also:
 . "$LIB_DIR"/init.bash
 
 profile_names=()
-
 while getopts ":C:p:h" option; do
     case $option in
     C) CONFIG_DIR=$OPTARG ;;
     p) profile_names+=("$OPTARG") ;;
     h)
-        printf "$usage\n"
-        exit 0
+        printf "%s\n" "$usage"
+        exit
         ;;
     :)
         printf "%s: option missing argument: -%s\n" "$0" "$OPTARG" >&2
@@ -58,26 +58,20 @@ while getopts ":C:p:h" option; do
 done
 shift $((OPTIND - 1))
 
-export LIB_DIR CONFIG_DIR
-
 if [[ ! -v 1 || -z $1 ]]; then
     printf "%s: the first argument must be an action\n" "$0" >&2
     exit 2
 fi
-action=$1
+action_name=$1
 
-case $action in
-create | prune) ;;
-*)
-    printf "%s: invalid action: %s\n" "$0" "$action" >&2
+if [[ ! $action_name =~ ^(create|prune)$ ]]; then
+    printf "%s: invalid action: %s\n" "$0" "$action_name" >&2
     exit 1
-    ;;
-esac
+fi
 
 export PROFILES_DIR=$CONFIG_DIR/profile.d
 export DEFAULTS_FILE=$CONFIG_DIR/defaults.conf
 
-declare -a profile_files
 if ((${#profile_names[@]} > 0)); then
     profile_files=()
     while IFS= read -r -d '' profile_name; do
@@ -111,8 +105,8 @@ done
 for profile_file in "${profile_files[@]}"; do
     load_profile "$profile_file"
 
-    if ! "$action"; then
-        printf "%s: unable to perform action '%s' for profile: %q\n" "$0" "$action" "$profile_file" >&2
+    if ! action_"$action_name"; then
+        printf "%s: unable to perform action '%s' for profile: %q\n" "$0" "$action_name" "$profile_file" >&2
         exit 1
     fi
 done
