Rename profile lib to config

diff --git a/bin/btrfs-snapshots b/bin/btrfs-snapshots
--- a/bin/btrfs-snapshots
+++ b/bin/btrfs-snapshots
@@ -79,31 +79,25 @@ create | prune | list) ;;
     ;;
 esac
 
-profile_dir=$CONFIG_DIR/profile.d
+export PROFILES_DIR=$CONFIG_DIR/profile.d
 
 declare -a profile_files
 
 if ((${#profile_names[@]} > 0)); then
-    profile_files=()
-
-    while IFS= read -r -d '' profile_name; do
-        profile_file=$profile_dir/$profile_name.conf
-
-        if [[ ! -f $profile_file ]]; then
-            printf "$TEXT_PROFILE_MISSING\n" "$profile_file" >&2
-            exit 1
-        fi
-
-        profile_files+=("$profile_file")
-    done < <(sort -zu < <(printf "%s\0" "${profile_names[@]}"))
+    readarray -t -d '' profile_files < <(sort -zu < <(printf "$PROFILES_DIR/%s.conf\0" "${profile_names[@]}"))
 else
-    profile_files=("$profile_dir"/*.conf)
+    profile_files=("$PROFILES_DIR"/*.conf)
 fi
 
-unset profile_{name{,s},file,dir}
+unset profile_names
 
 for PROFILE_FILE in "${profile_files[@]}"; do
     export PROFILE_FILE
+
+    if [[ ! -f $PROFILE_FILE ]]; then
+        printf "$TEXT_PROFILE_MISSING\n" "$PROFILE_FILE" >&2
+        exit 1
+    fi
 
     if ! load_profile; then
         printf "$TEXT_PROFILE_LOAD_FAILED\n" "$PROFILE_FILE" >&2
