style(scripts): adopt style improvements from template
Over time, I've made some small style improvements which start in the
template that I use to build other bash projects. This change just
brings in some of those.

diff --git a/scripts/test1 b/scripts/test1
--- a/scripts/test1
+++ b/scripts/test1
@@ -11,12 +11,12 @@ self_name=${0##*/}
 
 test_file=${1:?missing test file}
 
-TEMP_DIR=$(mktemp -td "$self_name".XXXXXXXXXX)
+TEMP_DIR=$(mktemp -td -- "$self_name.$$".XXXXXXXXXX)
 trap 'rm -rf -- "$TEMP_DIR"' EXIT
 
 export TEMP_DIR
 
 if ! "$test_file"; then
-    printf "%s: test failed: %q\n" "$self_name" "$test_file" >&2
+    printf "test failed: %q\n" "$test_file" >&2
     exit 1
 fi
