Safer printf formatting

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -11,11 +11,11 @@ run_test() {
     local file=$1
 
     if ((${TESTS_VERBOSE:-0})); then
-        printf "Running test: %s\n" "$file"
+        printf "Running test: %q\n" "$file"
     fi
 
     if ! "$file"; then
-        printf "Test failed: %s\n" "$file" >&2
+        printf "Test failed: %q\n" "$file" >&2
         return 1
     fi
 }
