Restructure a little bit

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,23 +2,97 @@
 
 set -euo pipefail
 
-export PATH=$PWD/tests/bin:$PWD/bin:$PATH
+self_name=${0##*/}
 
-export LIB_DIR=$PWD/lib
-export TESTS_LIB_DIR=$PWD/tests/lib
+ROOT_DIR=$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")
+
+USAGE="Run tests.
+
+If parallel is installed, it will be used to run tests concurrently.
+
+Usage:
+    $self_name [OPTIONS] [PATTERN...]
+
+Options:
+    -h         show this help text and exit
+
+    -i         match PATTERN case-insensitively
+
+    -v         print every test that's run, regardless of failures
+
+Arguments:
+    PATTERN    only test files matching PATTERN
+"
 
 run_test() {
-    local file=$1
+    local test_file=${1:?missing test file}
 
-    if ((${TESTS_VERBOSE:-0})); then
-        printf "Running test: %q\n" "$file"
+    TEMP_DIR=$(mktemp -d -t "$TEST_RUNNER_NAME".XXXXXXXXXX)
+    printf -v cleanup "rm -r %q" "$TEMP_DIR"
+    trap '$cleanup' EXIT
+    export TEMP_DIR
+
+    if ((${TEST_VERBOSE:-0})); then
+        printf "running test: %q\n" "$test_file"
     fi
 
-    if ! "$file"; then
-        printf "Test failed: %q\n" "$file" >&2
-        return 1
+    export PATH=$ROOT_DIR/tests/bin:$PATH
+
+    if ! "$test_file"; then
+        printf "test failed: %q\n" "$test_file" >&2
+        exit 1
     fi
 }
+
+TEST_VERBOSE=0
+find_option="path"
+while getopts "ivh" option; do
+    case $option in
+    v)
+        TEST_VERBOSE=1
+        ;;
+    i)
+        find_option="ipath"
+        ;;
+    h)
+        printf "%s\n" "$USAGE"
+        exit 0
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+declare -a find_options=()
+if (($# > 1)); then
+    find_options+=("\\(")
+    for pattern in "$@"; do
+        find_options+=(-"$find_option" "*$pattern*" -o)
+    done
+    unset "find_options[-1]"
+    find_options+=("\\)")
+elif (($# > 0)); then
+    find_options+=(-"$find_option" "*$1*")
+fi
+
+if command -v parallel >/dev/null; then
+    executor=(parallel --shuf --jobs=0 --null)
+else
+    executor=(xargs -r -n1 --null)
+fi
+
+export -f run_test
+
+export ROOT_DIR
+export TEST_VERBOSE
+export TEST_RUNNER_NAME=${ROOT_DIR##*/}-$self_name
+
+export LIB_DIR=$ROOT_DIR/lib
+export TESTS_LIB_DIR=$ROOT_DIR/tests/lib
+export PATH=$ROOT_DIR/tests/bin:$ROOT_DIR/bin:$PATH
+
+find "$ROOT_DIR"/tests/{unit,integration} \
+    -type f -executable "${find_options[@]}" -print0 |
+    "${executor[@]}" run_test
 
 export -f run_test
 
